### ISSUE TITLE
Application not responding

### ISSUE THREAD

**Issue by michelinka123** [teahmarkstone/Supermarket-Environment#1]
I just downloaded the updated Supermarket repo and when I run main.py everything works but when I run my code with the socket_env.py, I see my code running in the terminal (it's printing all system.out statements, etc) but the simulation itself is not opening and saying "Application not responding". I don't think it's a pygame issue since pygame runs fine when I use main.py, and I haven't changed my code at all and it was working with the previous version of the supermarket environment. Am I missing something? Very confused.

**Comment by dkasenberg** [comment]
Any chance you could send everything that prints to the console when you run socket_env.py?  It's working fine on my machine.

**Comment by michelinka123** [comment]
<img width="509" alt="Screen Shot 2021-04-02 at 3 45 33 PM" src="https://user-images.githubusercontent.com/40838517/113448831-9193ee00-93ca-11eb-9d1e-e589a2841897.png">
<img width="244" alt="Screen Shot 2021-04-02 at 3 45 42 PM" src="https://user-images.githubusercontent.com/40838517/113448843-95277500-93ca-11eb-9113-e7fefc8ddf3c.png">
<img width="759" alt="Screen Shot 2021-04-02 at 3 45 54 PM" src="https://user-images.githubusercontent.com/40838517/113448866-a1abcd80-93ca-11eb-858e-3245341ef9d0.png">

As you can see it's printing all of my print statements that I have throughout my Java file (printing the shopping list, etc) but the simulation itself does not run.

**Comment by dkasenberg** [comment]
Okay. The simulation is running, but the game screen is displaying "not responding". You can't command-tab into the screen?

**Comment by michelinka123** [comment]
That's correct. Command-tabbing into the screen does not get it to pop up, same as clicking on it.

**Comment by dkasenberg** [comment]
Try pulling and see if it works better now.  I can't replicate the problem on my machine, but I think it might have something to do with the fact that pygame needs the event queue to be checked periodically. If that's the case, this should have fixed it.

**Comment by michelinka123** [comment]
Sorry I'm very new to github - when you say "pull" do you mean re-clone the repo? (and thanks so much for your help)

**Comment by dkasenberg** [comment]
You can get the changes onto your machine with

`git pull origin main`

**Comment by dkasenberg** [comment]
(you have to be in the directory to use the command)

**Comment by michelinka123** [comment]
Ok, I used the command "git pull origin main" in my Supermarket-Environment directory and then tried running my java file with the socket_env.py file again; same results.

**Comment by dkasenberg** [comment]
Hmmm. Any chance you could email me your code and how generally to run it, so I can see whether it's an OS-specific error or something?  (My @tufts.edu email address should be in the how-to document, and is exactly what you'd expect it to be)

**Comment by michelinka123** [comment]
Yup just emailed you! Thank you so much

**Comment by dkasenberg** [comment]
I haven't received an email yet -- could just be a delay in Tufts' email server or something. Try my gmail account (firstname dot lastname at gmail)

**Comment by michelinka123** [comment]
Sent!

**Comment by michelinka123** [comment]
<img width="730" alt="Screen Shot 2021-04-02 at 5 13 15 PM" src="https://user-images.githubusercontent.com/40838517/113454648-b8582180-93d6-11eb-902a-616b1397800f.png">

**Comment by dkasenberg** [comment]
Hmm, we'll have to try something else -- apparently gmail blocks JAR files and other executables.  Could you upload it to google drive or Box or something and then send me the link instead?
